[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "javalang>=0.13.0",
    "matplotlib>=3.10.0",
    "networkx>=3.4.2",
    "plantuml>=0.3.0",
    "sqlalchemy>=2.0.38",
    "streamlit>=1.42.1",
]
